##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: reactor-addons-demo
  devtools:
    add-properties: false
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest

app:
  async:
    withDLQRetry: true
    retryDelay: 5000
    maxRetries: 3


